const SOLAR_SYSTEM_PLANETS = [
  {
    name: "Mercury",
    type: "Terrestrial Planet",
    color: "#b8b0a5",
    glow: "rgba(223, 217, 209, 0.45)",
    radius: 7,
    orbitRadius: 90,
    orbitSpeed: 0.032,
    description: "Mercury is the smallest planet and the fastest traveler around the Sun, racing through space in just 88 Earth days.",
    diameter: "4,879 km",
    distanceFromSun: "57.9 million km",
    moons: "0",
    atmosphere: "Extremely thin exosphere of oxygen, sodium, hydrogen, helium, and potassium",
    composition: "A rocky world with an oversized iron core, ancient impact basins, cliffs, and heavily cratered terrain.",
    temperature: "-180 C to 430 C",
    orbitalPeriod: "88 Earth days",
    funFact: "A day-night cycle on Mercury lasts 176 Earth days, so one sunrise there takes a very long time to come around.",
    moonsData: []
  },
  {
    name: "Venus",
    type: "Terrestrial Planet",
    color: "#dba56e",
    glow: "rgba(255, 198, 128, 0.48)",
    radius: 11,
    orbitRadius: 130,
    orbitSpeed: 0.024,
    description: "Venus is wrapped in thick clouds and intense heat, making it the hottest planet in the solar system.",
    diameter: "12,104 km",
    distanceFromSun: "108.2 million km",
    moons: "0",
    atmosphere: "Dense carbon dioxide with sulfuric acid clouds",
    composition: "A rocky planet with volcanic plains, mountain ranges, and a crushing greenhouse atmosphere.",
    temperature: "Around 465 C",
    orbitalPeriod: "225 Earth days",
    funFact: "Venus spins backward compared with most planets, so the Sun would appear to rise in the west and set in the east.",
    moonsData: []
  },
  {
    name: "Earth",
    type: "Terrestrial Planet",
    color: "#4da6ff",
    glow: "rgba(112, 190, 255, 0.5)",
    radius: 12,
    orbitRadius: 172,
    orbitSpeed: 0.02,
    description: "Earth is the only known planet with liquid surface water, complex weather, and thriving life.",
    diameter: "12,742 km",
    distanceFromSun: "149.6 million km",
    moons: "1",
    atmosphere: "Nitrogen, oxygen, argon, water vapor, and trace gases",
    composition: "A rocky planet with oceans, continents, plate tectonics, and a protective magnetic field.",
    temperature: "Average 15 C",
    orbitalPeriod: "365 days",
    funFact: "About 71% of Earth's surface is covered in water, giving it the brilliant blue appearance seen from space.",
    moonsData: [
      {
        name: "Moon",
        type: "Natural Satellite of Earth",
        color: "#d9dde6",
        glow: "rgba(222, 230, 246, 0.28)",
        radius: 3.2,
        orbitRadius: 24,
        orbitSpeed: 0.18,
        description: "Earth's Moon shapes ocean tides, stabilizes Earth's axial tilt, and lights up our night sky.",
        diameter: "3,475 km",
        distanceFromSun: "149.6 million km with Earth",
        moons: "0",
        atmosphere: "Extremely thin exosphere",
        composition: "Rocky body with ancient lava plains, bright highlands, and impact craters.",
        temperature: "-173 C to 127 C",
        orbitalPeriod: "27.3 Earth days",
        funFact: "The same side of the Moon always faces Earth because its rotation period matches its orbital period."
      }
    ]
  },
  {
    name: "Mars",
    type: "Terrestrial Planet",
    color: "#d97554",
    glow: "rgba(255, 136, 94, 0.44)",
    radius: 9,
    orbitRadius: 220,
    orbitSpeed: 0.016,
    description: "Mars is a dusty, desert-like world with giant volcanoes, deep canyons, and strong evidence of ancient water.",
    diameter: "6,779 km",
    distanceFromSun: "227.9 million km",
    moons: "2",
    atmosphere: "Thin carbon dioxide atmosphere with nitrogen and argon",
    composition: "An iron-rich rocky planet coated in rust-colored dust, polar ice caps, and basaltic plains.",
    temperature: "Average -63 C",
    orbitalPeriod: "687 Earth days",
    funFact: "Olympus Mons on Mars is the tallest known volcano in the solar system, towering about three times higher than Mount Everest.",
    moonsData: [
      {
        name: "Phobos",
        type: "Natural Satellite of Mars",
        color: "#9a8b79",
        glow: "rgba(177, 158, 137, 0.22)",
        radius: 2.5,
        orbitRadius: 18,
        orbitSpeed: 0.34,
        description: "Phobos is the larger and closer moon of Mars, skimming low above the Martian surface.",
        diameter: "22.5 km",
        distanceFromSun: "227.9 million km with Mars",
        moons: "0",
        atmosphere: "None detected",
        composition: "Dark, irregular rocky body covered in dust and impact scars.",
        temperature: "Around -40 C",
        orbitalPeriod: "7.7 hours",
        funFact: "Phobos rises in the west and sets in the east on Mars because it orbits faster than Mars rotates."
      },
      {
        name: "Deimos",
        type: "Natural Satellite of Mars",
        color: "#b4a48e",
        glow: "rgba(204, 188, 161, 0.18)",
        radius: 2.2,
        orbitRadius: 26,
        orbitSpeed: 0.22,
        description: "Deimos is the smaller, more distant moon of Mars and looks like a smooth drifting pebble in space.",
        diameter: "12.4 km",
        distanceFromSun: "227.9 million km with Mars",
        moons: "0",
        atmosphere: "None detected",
        composition: "A dark, porous rocky moon blanketed by loose regolith.",
        temperature: "Around -40 C",
        orbitalPeriod: "30.3 hours",
        funFact: "Because of its dusty surface, many of Deimos's small craters appear softened and partly filled in."
      }
    ]
  },
  {
    name: "Ceres",
    type: "Dwarf Planet",
    color: "#9fa7b4",
    glow: "rgba(187, 199, 218, 0.3)",
    radius: 5,
    orbitRadius: 264,
    orbitSpeed: 0.012,
    description: "Ceres is the largest object in the asteroid belt and the closest dwarf planet to the Sun, sitting between the rocky inner planets and the gas giants.",
    diameter: "939 km",
    distanceFromSun: "413.7 million km",
    moons: "0",
    atmosphere: "Extremely thin temporary water-vapor exosphere",
    composition: "A mix of rock, clay, salts, and water ice with bright deposits in some impact craters.",
    temperature: "Around -105 C",
    orbitalPeriod: "4.6 Earth years",
    funFact: "Bright salt deposits inside Occator Crater made Ceres one of the most surprising worlds visited by NASA's Dawn mission.",
    moonsData: []
  },
  {
    name: "Jupiter",
    type: "Gas Giant",
    color: "#d7b08c",
    glow: "rgba(255, 208, 171, 0.4)",
    radius: 24,
    orbitRadius: 305,
    orbitSpeed: 0.009,
    description: "Jupiter is the solar system's giant guardian, famous for its swirling cloud bands and the Great Red Spot storm.",
    diameter: "139,820 km",
    distanceFromSun: "778.5 million km",
    moons: "95",
    atmosphere: "Mostly hydrogen and helium with ammonia, methane, and water traces",
    composition: "A huge gas giant with layered clouds, powerful storms, and a likely dense core hidden deep below.",
    temperature: "Cloud tops around -145 C",
    orbitalPeriod: "11.86 Earth years",
    funFact: "Jupiter is so massive that more than 1,300 Earths could fit inside it by volume.",
    moonsData: [
      {
        name: "Io",
        type: "Natural Satellite of Jupiter",
        color: "#e8d66b",
        glow: "rgba(243, 228, 133, 0.25)",
        radius: 3,
        orbitRadius: 34,
        orbitSpeed: 0.23,
        description: "Io is a volcanic moon covered with sulfur-rich plains, lava flows, and constantly reshaped terrain.",
        diameter: "3,643 km",
        distanceFromSun: "778.5 million km with Jupiter",
        moons: "0",
        atmosphere: "Very thin sulfur dioxide atmosphere",
        composition: "Rocky interior with widespread volcanism and colorful sulfur deposits.",
        temperature: "Average -130 C",
        orbitalPeriod: "1.77 Earth days",
        funFact: "Io is the most volcanically active world known in the entire solar system."
      },
      {
        name: "Europa",
        type: "Natural Satellite of Jupiter",
        color: "#d7cab8",
        glow: "rgba(227, 217, 198, 0.22)",
        radius: 3.1,
        orbitRadius: 42,
        orbitSpeed: 0.18,
        description: "Europa has a bright icy crust and likely hides a global saltwater ocean beneath that frozen shell.",
        diameter: "3,122 km",
        distanceFromSun: "778.5 million km with Jupiter",
        moons: "0",
        atmosphere: "Extremely thin oxygen atmosphere",
        composition: "Water ice crust over a rocky interior and suspected subsurface ocean.",
        temperature: "Around -160 C",
        orbitalPeriod: "3.55 Earth days",
        funFact: "Europa is one of the strongest candidates in the solar system for harboring conditions friendly to life."
      },
      {
        name: "Ganymede",
        type: "Natural Satellite of Jupiter",
        color: "#8d8f91",
        glow: "rgba(175, 180, 182, 0.22)",
        radius: 3.5,
        orbitRadius: 52,
        orbitSpeed: 0.14,
        description: "Ganymede is the largest moon in the solar system and is even bigger than the planet Mercury.",
        diameter: "5,268 km",
        distanceFromSun: "778.5 million km with Jupiter",
        moons: "0",
        atmosphere: "Very thin oxygen atmosphere",
        composition: "Rock and water ice with grooves, dark regions, and its own magnetic field.",
        temperature: "Around -163 C",
        orbitalPeriod: "7.15 Earth days",
        funFact: "Ganymede is the only moon known to generate its own internal magnetic field."
      },
      {
        name: "Callisto",
        type: "Natural Satellite of Jupiter",
        color: "#7d736e",
        glow: "rgba(154, 143, 136, 0.2)",
        radius: 3.2,
        orbitRadius: 63,
        orbitSpeed: 0.11,
        description: "Callisto is an ancient, crater-saturated moon whose battered surface preserves a long history of impacts.",
        diameter: "4,821 km",
        distanceFromSun: "778.5 million km with Jupiter",
        moons: "0",
        atmosphere: "Extremely thin carbon dioxide and oxygen",
        composition: "A mix of rock and ice with one of the oldest visible surfaces in the solar system.",
        temperature: "Around -139 C",
        orbitalPeriod: "16.69 Earth days",
        funFact: "The giant Valhalla impact structure on Callisto spans thousands of kilometers in concentric rings."
      }
    ]
  },
  {
    name: "Saturn",
    type: "Gas Giant",
    color: "#e2c989",
    glow: "rgba(255, 225, 153, 0.4)",
    radius: 21,
    orbitRadius: 390,
    orbitSpeed: 0.0065,
    hasRings: true,
    description: "Saturn is best known for its dazzling ring system, made of countless icy particles and rocky fragments.",
    diameter: "116,460 km",
    distanceFromSun: "1.43 billion km",
    moons: "146",
    atmosphere: "Hydrogen and helium with methane and ammonia traces",
    composition: "A low-density gas giant with layered clouds, a deep interior, and a spectacular ring network.",
    temperature: "Cloud tops around -178 C",
    orbitalPeriod: "29.45 Earth years",
    funFact: "Saturn is less dense than water, which means it would float if there were an ocean large enough to hold it.",
    moonsData: [
      {
        name: "Titan",
        type: "Natural Satellite of Saturn",
        color: "#d9a968",
        glow: "rgba(236, 190, 121, 0.24)",
        radius: 3.5,
        orbitRadius: 34,
        orbitSpeed: 0.14,
        description: "Titan is a hazy, orange moon with rivers, lakes, and rain made from liquid methane and ethane.",
        diameter: "5,149 km",
        distanceFromSun: "1.43 billion km with Saturn",
        moons: "0",
        atmosphere: "Dense nitrogen-rich atmosphere with methane",
        composition: "Icy crust, hydrocarbon lakes, and a complex layered atmosphere.",
        temperature: "Around -179 C",
        orbitalPeriod: "15.95 Earth days",
        funFact: "Titan is the only moon in the solar system with a thick atmosphere and stable liquid on its surface."
      },
      {
        name: "Enceladus",
        type: "Natural Satellite of Saturn",
        color: "#eef3ff",
        glow: "rgba(232, 240, 255, 0.28)",
        radius: 2.8,
        orbitRadius: 42,
        orbitSpeed: 0.22,
        description: "Enceladus is a bright icy moon that sprays towering plumes of water vapor and ice from its south pole.",
        diameter: "504 km",
        distanceFromSun: "1.43 billion km with Saturn",
        moons: "0",
        atmosphere: "Thin water vapor atmosphere near plume regions",
        composition: "Ice-covered surface over a global subsurface ocean.",
        temperature: "Around -201 C",
        orbitalPeriod: "1.37 Earth days",
        funFact: "The geysers of Enceladus help feed Saturn's diffuse E ring."
      },
      {
        name: "Rhea",
        type: "Natural Satellite of Saturn",
        color: "#c7c9d0",
        glow: "rgba(210, 214, 224, 0.18)",
        radius: 2.9,
        orbitRadius: 50,
        orbitSpeed: 0.12,
        description: "Rhea is a cratered icy moon with bright wispy markings stretched across parts of its surface.",
        diameter: "1,528 km",
        distanceFromSun: "1.43 billion km with Saturn",
        moons: "0",
        atmosphere: "Extremely tenuous oxygen and carbon dioxide",
        composition: "Mostly water ice with a smaller fraction of rocky material.",
        temperature: "Around -174 C",
        orbitalPeriod: "4.52 Earth days",
        funFact: "Rhea may have once supported a faint ring system of its own, though evidence remains debated."
      },
      {
        name: "Iapetus",
        type: "Natural Satellite of Saturn",
        color: "#9f8b7a",
        glow: "rgba(171, 152, 136, 0.2)",
        radius: 2.7,
        orbitRadius: 62,
        orbitSpeed: 0.08,
        description: "Iapetus is famous for its dramatic two-tone coloring, with one hemisphere much darker than the other.",
        diameter: "1,471 km",
        distanceFromSun: "1.43 billion km with Saturn",
        moons: "0",
        atmosphere: "No substantial atmosphere",
        composition: "Mostly ice and rock with a strange equatorial ridge.",
        temperature: "Around -143 C",
        orbitalPeriod: "79.32 Earth days",
        funFact: "A giant ridge runs around Iapetus like a belt, making the moon look almost walnut-shaped."
      }
    ]
  },
  {
    name: "Uranus",
    type: "Ice Giant",
    color: "#8bd9e6",
    glow: "rgba(148, 231, 255, 0.38)",
    radius: 17,
    orbitRadius: 468,
    orbitSpeed: 0.0045,
    description: "Uranus is a pale blue ice giant that rotates on its side, giving it one of the strangest tilts in the solar system.",
    diameter: "50,724 km",
    distanceFromSun: "2.87 billion km",
    moons: "28",
    atmosphere: "Hydrogen, helium, and methane",
    composition: "An ice giant made of water, ammonia, and methane ices above a rocky interior.",
    temperature: "Around -224 C",
    orbitalPeriod: "84 Earth years",
    funFact: "Its dramatic axial tilt makes Uranus seem to roll around the Sun instead of spinning upright like most planets.",
    moonsData: [
      {
        name: "Titania",
        type: "Natural Satellite of Uranus",
        color: "#c8d2da",
        glow: "rgba(207, 218, 226, 0.2)",
        radius: 3.1,
        orbitRadius: 30,
        orbitSpeed: 0.12,
        description: "Titania is the largest moon of Uranus, marked by icy plains, long faults, and large impact basins.",
        diameter: "1,578 km",
        distanceFromSun: "2.87 billion km with Uranus",
        moons: "0",
        atmosphere: "Very thin carbon dioxide",
        composition: "Roughly equal parts water ice and rock.",
        temperature: "Around -203 C",
        orbitalPeriod: "8.71 Earth days",
        funFact: "Many Uranian moons, including Titania, are named after literary characters from Shakespeare and Pope."
      },
      {
        name: "Oberon",
        type: "Natural Satellite of Uranus",
        color: "#a4aab2",
        glow: "rgba(183, 191, 202, 0.16)",
        radius: 3,
        orbitRadius: 38,
        orbitSpeed: 0.1,
        description: "Oberon is a dark, cratered outer moon of Uranus with hints of bright fresh impact deposits.",
        diameter: "1,523 km",
        distanceFromSun: "2.87 billion km with Uranus",
        moons: "0",
        atmosphere: "No substantial atmosphere",
        composition: "Mixture of ice and rock with heavy impact cratering.",
        temperature: "Around -203 C",
        orbitalPeriod: "13.46 Earth days",
        funFact: "Oberon orbits so far from Uranus that it spends much of its time in deep, isolated darkness."
      },
      {
        name: "Ariel",
        type: "Natural Satellite of Uranus",
        color: "#d8dde2",
        glow: "rgba(228, 234, 239, 0.18)",
        radius: 2.8,
        orbitRadius: 22,
        orbitSpeed: 0.16,
        description: "Ariel has one of the brightest and youngest-looking surfaces among Uranus's large moons.",
        diameter: "1,158 km",
        distanceFromSun: "2.87 billion km with Uranus",
        moons: "0",
        atmosphere: "No substantial atmosphere",
        composition: "Icy crust with canyons, ridges, and resurfaced plains.",
        temperature: "Around -213 C",
        orbitalPeriod: "2.52 Earth days",
        funFact: "Ariel's surface looks geologically refreshed compared with many older, more heavily cratered moons."
      },
      {
        name: "Miranda",
        type: "Natural Satellite of Uranus",
        color: "#b7c0c8",
        glow: "rgba(194, 204, 214, 0.18)",
        radius: 2.4,
        orbitRadius: 16,
        orbitSpeed: 0.2,
        description: "Miranda is a small moon with giant cliffs and patchwork terrain that looks stitched together from different worlds.",
        diameter: "472 km",
        distanceFromSun: "2.87 billion km with Uranus",
        moons: "0",
        atmosphere: "No substantial atmosphere",
        composition: "Mostly ice with rocky material and dramatic tectonic scars.",
        temperature: "Around -187 C",
        orbitalPeriod: "1.41 Earth days",
        funFact: "Miranda is home to Verona Rupes, one of the tallest known cliffs in the solar system."
      }
    ]
  },
  {
    name: "Neptune",
    type: "Ice Giant",
    color: "#496fff",
    glow: "rgba(103, 134, 255, 0.46)",
    radius: 17,
    orbitRadius: 540,
    orbitSpeed: 0.0035,
    description: "Neptune is a deep blue, windy world far from the Sun, where storms can rage at incredible speeds.",
    diameter: "49,244 km",
    distanceFromSun: "4.5 billion km",
    moons: "16",
    atmosphere: "Hydrogen, helium, and methane",
    composition: "An ice giant with a dynamic atmosphere, frigid temperatures, and a dense mantle of icy materials.",
    temperature: "Around -214 C",
    orbitalPeriod: "164.8 Earth years",
    funFact: "Neptune has some of the fastest winds in the solar system, with speeds that can exceed 2,000 km/h.",
    moonsData: [
      {
        name: "Triton",
        type: "Natural Satellite of Neptune",
        color: "#d4c0b3",
        glow: "rgba(226, 209, 197, 0.22)",
        radius: 3.3,
        orbitRadius: 28,
        orbitSpeed: -0.1,
        description: "Triton is a cold, geologically active moon that orbits Neptune in a rare backward, or retrograde, direction.",
        diameter: "2,710 km",
        distanceFromSun: "4.5 billion km with Neptune",
        moons: "0",
        atmosphere: "Thin nitrogen atmosphere with methane traces",
        composition: "Icy crust with nitrogen frost, water ice, and cryovolcanic features.",
        temperature: "Around -235 C",
        orbitalPeriod: "5.88 Earth days",
        funFact: "Triton likely began life as a Kuiper Belt object before Neptune captured it."
      },
      {
        name: "Proteus",
        type: "Natural Satellite of Neptune",
        color: "#8c8781",
        glow: "rgba(154, 149, 144, 0.16)",
        radius: 2.6,
        orbitRadius: 18,
        orbitSpeed: 0.18,
        description: "Proteus is a dark, irregular moon that is nearly as large as a body of its shape can be without collapsing into a sphere.",
        diameter: "420 km",
        distanceFromSun: "4.5 billion km with Neptune",
        moons: "0",
        atmosphere: "No substantial atmosphere",
        composition: "Dark icy-rocky body with many impact scars.",
        temperature: "Around -223 C",
        orbitalPeriod: "1.12 Earth days",
        funFact: "Proteus is one of the largest irregularly shaped moons in the solar system."
      },
      {
        name: "Nereid",
        type: "Natural Satellite of Neptune",
        color: "#b9bcc1",
        glow: "rgba(208, 212, 219, 0.16)",
        radius: 2.4,
        orbitRadius: 40,
        orbitSpeed: 0.06,
        description: "Nereid travels on a very stretched-out orbit, wandering far from Neptune before swinging back in.",
        diameter: "340 km",
        distanceFromSun: "4.5 billion km with Neptune",
        moons: "0",
        atmosphere: "No substantial atmosphere",
        composition: "Icy moon with a highly eccentric orbit.",
        temperature: "Around -220 C",
        orbitalPeriod: "360 Earth days",
        funFact: "Nereid has one of the most eccentric orbits known for any large planetary moon."
      }
    ]
  },
  {
    name: "Pluto",
    type: "Dwarf Planet",
    color: "#d9c0a8",
    glow: "rgba(228, 205, 182, 0.28)",
    radius: 5.2,
    orbitRadius: 625,
    orbitSpeed: 0.0028,
    description: "Pluto is a distant icy dwarf planet in the Kuiper Belt, known for its heart-shaped plain and surprisingly varied surface.",
    diameter: "2,377 km",
    distanceFromSun: "5.9 billion km on average",
    moons: "5",
    atmosphere: "Thin nitrogen atmosphere with methane and carbon monoxide",
    composition: "A frozen world of nitrogen ice, methane ice, water ice mountains, and ancient impact terrain.",
    temperature: "Around -229 C",
    orbitalPeriod: "248 Earth years",
    funFact: "Pluto's moon Charon is so large that the pair orbit a point in space outside Pluto itself.",
    moonsData: [
      {
        name: "Charon",
        type: "Natural Satellite of Pluto",
        color: "#b9b0aa",
        glow: "rgba(207, 198, 191, 0.18)",
        radius: 2.8,
        orbitRadius: 16,
        orbitSpeed: 0.14,
        description: "Charon is Pluto's largest moon, so large that Pluto and Charon behave almost like a double world system.",
        diameter: "1,212 km",
        distanceFromSun: "5.9 billion km with Pluto",
        moons: "0",
        atmosphere: "No substantial atmosphere detected",
        composition: "A cold mix of water ice and rock with giant chasms and reddish polar staining.",
        temperature: "Around -220 C",
        orbitalPeriod: "6.39 Earth days",
        funFact: "Pluto and Charon orbit a shared point in space that lies outside Pluto itself."
      },
      {
        name: "Nix",
        type: "Natural Satellite of Pluto",
        color: "#d4d2cf",
        glow: "rgba(222, 220, 216, 0.14)",
        radius: 1.8,
        orbitRadius: 24,
        orbitSpeed: 0.1,
        description: "Nix is a small irregular moon of Pluto with a bright icy surface and a rapid tumbling rotation.",
        diameter: "49 km",
        distanceFromSun: "5.9 billion km with Pluto",
        moons: "0",
        atmosphere: "None detected",
        composition: "Bright water-ice-rich body with an uneven elongated shape.",
        temperature: "Around -230 C",
        orbitalPeriod: "24.9 Earth days",
        funFact: "Nix does not keep one face pointed at Pluto and instead tumbles chaotically through space."
      }
    ]
  },
  {
    name: "Haumea",
    type: "Dwarf Planet",
    color: "#cfd8ea",
    glow: "rgba(208, 221, 244, 0.24)",
    radius: 4.7,
    orbitRadius: 690,
    orbitSpeed: 0.0023,
    description: "Haumea is a fast-spinning dwarf planet with an elongated shape, a bright icy surface, and a tiny ring.",
    diameter: "About 1,960 km long axis",
    distanceFromSun: "6.5 billion km on average",
    moons: "2",
    atmosphere: "No substantial atmosphere detected",
    composition: "Mostly water ice over a rocky interior, shaped by rapid rotation and an ancient collision.",
    temperature: "Around -241 C",
    orbitalPeriod: "284 Earth years",
    funFact: "Haumea spins once in under four hours, making it one of the fastest-rotating large bodies in the solar system.",
    moonsData: [
      {
        name: "Hiiaka",
        type: "Natural Satellite of Haumea",
        color: "#d7e6f0",
        glow: "rgba(221, 235, 244, 0.16)",
        radius: 2.1,
        orbitRadius: 18,
        orbitSpeed: 0.11,
        description: "Hiiaka is the larger outer moon of Haumea and appears to be coated with bright crystalline water ice.",
        diameter: "About 320 km",
        distanceFromSun: "6.5 billion km with Haumea",
        moons: "0",
        atmosphere: "None detected",
        composition: "Icy body likely rich in water ice, probably formed by an ancient collision.",
        temperature: "Around -240 C",
        orbitalPeriod: "49 Earth days",
        funFact: "Hiiaka helped reveal that Haumea belongs to a family of icy collision fragments."
      },
      {
        name: "Namaka",
        type: "Natural Satellite of Haumea",
        color: "#bfcfe0",
        glow: "rgba(203, 215, 232, 0.14)",
        radius: 1.7,
        orbitRadius: 11,
        orbitSpeed: 0.17,
        description: "Namaka is the smaller inner moon of Haumea, moving on a tilted orbit influenced by Haumea's odd shape and fast spin.",
        diameter: "About 170 km",
        distanceFromSun: "6.5 billion km with Haumea",
        moons: "0",
        atmosphere: "None detected",
        composition: "Small icy moon likely created during the same collision that shaped Haumea.",
        temperature: "Around -240 C",
        orbitalPeriod: "18 Earth days",
        funFact: "Namaka's orbit is unusually tilted, making the Haumea system more dynamically complex than it first appears."
      }
    ]
  },
  {
    name: "Makemake",
    type: "Dwarf Planet",
    color: "#c58f68",
    glow: "rgba(224, 165, 126, 0.22)",
    radius: 4.8,
    orbitRadius: 740,
    orbitSpeed: 0.002,
    description: "Makemake is a reddish dwarf planet in the Kuiper Belt with a bright frozen surface and a very thin atmosphere that may appear seasonally.",
    diameter: "1,430 km",
    distanceFromSun: "6.8 billion km on average",
    moons: "1",
    atmosphere: "A possible seasonal thin methane atmosphere",
    composition: "Methane, ethane, and likely nitrogen ices covering a cold rocky-icy body.",
    temperature: "Around -239 C",
    orbitalPeriod: "305 Earth years",
    funFact: "Makemake was discovered shortly after Easter in 2005, which helped inspire its nickname during the discovery period.",
    moonsData: [
      {
        name: "MK 2",
        type: "Natural Satellite of Makemake",
        color: "#c6c2ba",
        glow: "rgba(214, 210, 202, 0.14)",
        radius: 1.7,
        orbitRadius: 14,
        orbitSpeed: 0.12,
        description: "MK 2 is Makemake's tiny dark moon, discovered long after Makemake itself and still only partly understood.",
        diameter: "About 175 km",
        distanceFromSun: "6.8 billion km with Makemake",
        moons: "0",
        atmosphere: "None detected",
        composition: "Likely a dark icy-rocky body with low reflectivity compared with Makemake.",
        temperature: "Around -239 C",
        orbitalPeriod: "About 12 days",
        funFact: "Before its moon was found, Makemake's mass was much harder for astronomers to estimate accurately."
      }
    ]
  },
  {
    name: "Eris",
    type: "Dwarf Planet",
    color: "#e3e7f0",
    glow: "rgba(231, 236, 245, 0.24)",
    radius: 5.1,
    orbitRadius: 860,
    orbitSpeed: 0.0012,
    description: "Eris is one of the most distant known dwarf planets, an icy world beyond the main Kuiper Belt in the scattered disk.",
    diameter: "2,326 km",
    distanceFromSun: "10.1 billion km on average",
    moons: "1",
    atmosphere: "Likely a temporary thin atmosphere near closest approach to the Sun",
    composition: "Rocky interior with a highly reflective surface coated in methane ice.",
    temperature: "Around -231 C",
    orbitalPeriod: "557 Earth years",
    funFact: "The discovery of Eris helped trigger the debate that led to Pluto being officially classified as a dwarf planet.",
    moonsData: [
      {
        name: "Dysnomia",
        type: "Natural Satellite of Eris",
        color: "#c8d0db",
        glow: "rgba(214, 221, 231, 0.14)",
        radius: 2,
        orbitRadius: 15,
        orbitSpeed: 0.1,
        description: "Dysnomia is Eris's lone known moon, circling one of the most distant named dwarf planets in the solar system.",
        diameter: "About 700 km",
        distanceFromSun: "10.1 billion km with Eris",
        moons: "0",
        atmosphere: "None detected",
        composition: "Likely an icy-rocky moon formed or captured early in the Eris system's history.",
        temperature: "Around -231 C",
        orbitalPeriod: "15.8 Earth days",
        funFact: "Dysnomia was crucial in helping astronomers measure the mass of Eris."
      }
    ]
  }
];
